# visible & thermal camera intrinsics for flir one pro
visible_camera:
  H: 1440
  W: 1080
  HFOV: 55
  VFOV: 43
  fx: null
  fy: null
  cx: null
  cy: null

thermal_camera:
  H: 640
  W: 480
  HFOV: 55
  VFOV: 43
  fx: null
  fy: null
  cx: null
  cy: null

# affine parameters
angle: 0 # angle (in degrees)
hx:    0
hy:    0
sx:    1
sy:    1
tx:    0 # translation (in pixels)
ty:    0

# radial and tangential distortion coefficients
k1: 0
k2: 0
k3: 0
p1: 0
p2: 0